
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ValoracionNoValidaException", targetNamespace = "http://webservices/")
public class ValoracionNoValidaException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ValoracionNoValidaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ValoracionNoValidaException_Exception(String message, ValoracionNoValidaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ValoracionNoValidaException_Exception(String message, ValoracionNoValidaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.ValoracionNoValidaException
     */
    public ValoracionNoValidaException getFaultInfo() {
        return faultInfo;
    }

}
