
package webservices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "YaExisteCategoriaException", targetNamespace = "http://webservices/")
public class YaExisteCategoriaException_Exception
    extends java.lang.Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private YaExisteCategoriaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public YaExisteCategoriaException_Exception(String message, YaExisteCategoriaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public YaExisteCategoriaException_Exception(String message, YaExisteCategoriaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: webservices.YaExisteCategoriaException
     */
    public YaExisteCategoriaException getFaultInfo() {
        return faultInfo;
    }

}
